// <auto-generated />
using Caminhoes.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Caminhoes.Api.Migrations
{
    [DbContext(typeof(CaminhoesDbContext))]
    partial class CaminhoesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Caminhoes.Api.Models.Caminhao", b =>
                {
                    b.Property<string>("CodigoChassi")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("Modelo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Planta")
                        .HasColumnType("INTEGER");

                    b.HasKey("CodigoChassi");

                    b.HasIndex("CodigoChassi")
                        .IsUnique();

                    b.ToTable("Caminhoes");
                });
#pragma warning restore 612, 618
        }
    }
}
